### ISSUE TITLE
Ship types (index.d.ts) to work with Typescript

### ISSUE THREAD

**Issue by jhm-ciberman** [toji/gl-matrix#323] opened 2018-06-26 21:54 UTC
Hello. I want to propose to ship the types.d.ts file to work with typescript with the gl-matrix. 

## Why? 
Because in this way the types could be updated with each change. For example. The version that is now in DefinetelyTyped (The place with all the types definitions for all npm packages) is outdated and not contain the new mat4.targetTo(....) method. 

## How? 
Simply copy this file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gl-matrix/index.d.ts

to the gl-matrix repo root, and then add the `types` field to the package,json:
```
{
    "name": "awesome",
    "author": "Vandelay Industries",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "types": "./index.d.ts"
}
```

More instructions here: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Then npm publish the new version. And that's all.. you will have thousands of Typescript developers happy. :) 

If you want, you can also add the mat4.targetAt(...) method to the index.d.ts. It should be easy to add. Also, you can add another missing methods if you wish.

**Comment by Epskampie** [comment] 2018-08-30 16:03
Hey @jhm-ciberman, have you considered contributing to the definitelytyped definition by adding the mat4.targetTo definition? This way the developers have more time to just work on gl-matrix.

It's quite easy, just make a pull request in the definitelytyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gl-matrix . They usually get merged in a week or so. Here's a guide: https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

**Comment by dcbrwn** [comment] 2018-09-04 13:54
@Epskampie definitely typed project is deprecated. @jhm-ciberman proposes correct way to do this. Btw gl-matrix devs already kinda work on typings by specifying JSDocs. TS compiler checks them, but since they are a bit incomplete it often complains about type mismatches.

**Comment by stefnotch** [comment] 2018-09-04 14:04
> but since they are a bit incomplete it often complains about type mismatches

That's a problem that I can, and should definitely address. Any examples of types that are incomplete/wrong?

**Comment by dcbrwn** [comment] 2018-09-06 08:06
@stefnotch not sure what causes this, but when type is explicitly declared for a variable, typescript built into webstorm complains that it's not correct. if type is not declared and inferred - all is just fine.

![image](https://user-images.githubusercontent.com/12214069/45143747-c153c880-b1c4-11e8-8efa-5c04e5398895.png)

manually running TSC in terminal emits to errors nor warnings. probably it's an issue with webstorm.

**Comment by stefnotch** [comment] 2018-09-06 08:28
I tried reproducing it with Visual Studio Code (I don't have a copy of WebStorm lying around) and did manage to run into one issue with the current JSDoc types. 

![image](https://user-images.githubusercontent.com/10220080/45144743-44722000-b1bf-11e8-872e-da3aab05d01c.png)

**Comment by TimvanScherpenzeel** [comment] 2018-12-07 18:54
With the new 3.0.0 release coming up I expect some quite major changes with the current types on DefinetelyTyped. Would there be interest in shipping types along with the library itself? Or would it be best to continue on DefinetelyTyped? (And if so does it support `@next` for the future release?).

Thank you for all the recent updates @stefnotch, very exciting to see that this library keeps evolving!

**Comment by stefnotch** [comment] 2018-12-07 21:07
Would updating the JSDoc comments be a viable alternative?

**Comment by dcbrwn** [comment] 2018-12-10 12:41
@stefnotch If no one is working on typings yet, I can do it.

**Comment by stefnotch** [comment] 2018-12-10 14:44
@dcbrwn Thank you for your kind offer; nobody is working on the typing so far. 😄 

I'm a big fan of TypeScript, however, is it worth the effort? The JSDoc comments already exist after all.
Also, there are various tools to convert the JSDoc comments to TypeScript. (I'd be perfectly fine with autogenerated TypeScript, as that wouldn't cause additional maintenance effort.)

**Comment by TimvanScherpenzeel** [comment] 2018-12-10 19:05
@dcbrwn thank you for your offer, I don't have a lot of experience with creating high quality typings myself but can help with going through the code and updating the JSDoc comments where necessary. Do you expect autogenerated types from JSDoc comments to be of high enough quality to use directly?

Currently there are typings up on [DefinetlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gl-matrix) but they are not up to date with the latest release `@next` release as mentioned earlier.

**Comment by stefnotch** [comment] 2018-12-11 20:48
Link to a relevant issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22770

**Comment by dcbrwn** [comment] 2018-12-16 17:09
I've spent a few hours today reading through discussions in related GH issues and trying to use [tsd-jsdoc](https://www.npmjs.com/package/tsd-jsdoc) to auto-generate typings. Tried to change JSDoc annotations to get some decent results, but no luck so far.

@stefnotch should I just proceed with what @jhm-ciberman originally proposed (copy-paste type definitions to gl-matrix repo and just update them)?

**Comment by spacejack** [comment] 2018-12-16 22:14
Just a few comments since I created the referred issue [#22770](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22770).

If you include types in gl-matrix then using other definitions is a bit of a headache for people who would prefer different types.

The current types on DefinitelyTyped are, IMO, over-opinionated. On the other hand some people might prefer to have nominal types and always use vec*.create rather than using vec* functions on other types of arrays.

A few other notes about including type defs in a JS project (being the maintainer of types for a JS library myself). We opted to keep the types separate even though the project maintainers are friendly to Typescript users.

* Releases are not held up by type issues
* Versions are not bumped due to type updates
* If desired, a user can easily npm install a different set of types.

Just to re-iterate my opinion from the DT thread:

* The "official" types should support the broadest use-cases
* Nominal type defs should be maintained as a separate npm library

**Comment by stefnotch** [comment] 2019-11-06 13:10
It seems like Typescript v3.7 makes it possible to [generate `.d.ts` files from JSDoc](
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs).

**Comment by stefnotch** [comment] 2020-02-13 20:13
I tried it out, and there is still this open issue in the TypeScript repository https://github.com/microsoft/TypeScript/issues/4433

**Closed** 2020-02-13 21:07 UTC
Labels: feature-request

**Comment by stefnotch** [comment] 2020-02-13 22:06
[gl-matrix now comes with a `.d.ts` file on npm](https://github.com/toji/gl-matrix/releases/tag/v.3.2.0)

The autogenerating of the `.d.ts` file is still rather hack-ish, but it's better than nothing.
