### ISSUE TITLE
mat4.lookAt behaving oddly

### ISSUE THREAD

**Issue by brett19** [toji/gl-matrix#139] opened 2014-11-06 12:31 UTC
For some reason, whenever I try to use lookAt to calculate my camera's rotation, I get all sorts of wierd behaviour, here is the code I have to use to get a reasonable rotation matrix.  Note that up_ is [0,0,1] (z-up), this.position is the camera's position, and vec is where we want to look.
P.S. The wierdness is in needing to invert the up matrix, and then invert the resulting quaternion.  Not doing these inversions gives me an incorrect result entirely.

``` javascript
vec3.negate(_tmpVec3, up_);
mat4.lookAt(_tmpMat4, this.position, vec, _tmpVec3);
mat3.fromMat4(_tmpMat3, _tmpMat4);
quat.fromMat3(this.rotation, _tmpMat3);
quat.normalize(this.rotation, this.rotation);
quat.invert(this.rotation, this.rotation);
```

**Comment by stefnotch** [comment] 2017-03-04 18:27
Is this still an issue? #134 is most likely fixed.

**Comment by brianchirls** [comment] 2018-03-03 22:01
I'm having the same problem.

Compare [this implementation](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js#L1413) to the [equivalent function at three.js](https://github.com/mrdoob/three.js/blob/dev/src/math/Matrix4.js#L363) and see that most of the computation is similar, but the resulting values are assigned to the outgoing matrix differently. I don't understand the math here, but I can confirm that the three.js implementation works fine.

**Comment by stefnotch** [comment] 2018-03-04 09:34
@brianchirls 
What happens if you use `targetTo` instead of `lookAt`?

**Comment by brianchirls** [comment] 2018-03-05 04:11
Yeah, that's much better.

What's the difference between the two functions? Seems like it may be worth more explicit documentation, especially if there's a discrepancy with three.js.

**Comment by stefnotch** [comment] 2018-03-05 06:05
https://github.com/toji/gl-matrix/issues/225

**Comment by brianchirls** [comment] 2018-03-05 18:35
@stefnotch Thanks for pointing that out. So:
1) three.js is "wrong" then?
2) This could probably still be better explained in the documentation, especially since it's different in three.js, which is a de facto "standard" for webgl (for better or worse).

**Comment by stefnotch** [comment] 2018-04-03 16:01
Merged

**Closed by stefnotch** 2018-04-03 16:01 UTC
