### ISSUE TITLE
dose it can only use in special matrix?

### ISSUE THREAD

**Issue by KylinLee** [toji/gl-matrix#406] opened 2020-10-05 02:54 UTC
I have read the document, it just include mat2~mat4,can I use gl-matrix in any matrix? such as 100×100 matrix.

**Comment by stefnotch** [comment] 2020-10-05 06:43
Duplicate of #168 .

gl-matrix isn't designed for bespoke matrices.

**Closed by stefnotch** 2020-10-05 06:43 UTC
