### ISSUE TITLE
How to solve 4X4 matrix multiply vertices 4?

### ISSUE THREAD

**Issue by Jim-Cen** [toji/gl-matrix#235] opened 2016-12-16 14:13 UTC
How to solve 4X4 matrix multiply vertices 4?
Other js has mat4.x(m) function, but gl-matrix has NOT.

**Comment by httpdigest** [comment] 2016-12-16 14:26
Duplicate of #232

**Comment by stefnotch** [comment] 2017-12-13 15:23
@toji This issue can be closed.

**Closed** 2018-03-30 13:01 UTC
