### ISSUE TITLE
Tests broken, pass regardless of what's in the code

### ISSUE THREAD

**Issue by jvorob** [toji/gl-matrix#260] opened 2017-08-15 19:29 UTC
It seems like the tests are all passing regardless of what is done to the code.
I tested this by replacing all instances of 
`out[0] = ...`
with
`out[0] = 1;`
in vec2.js, and all the tests still pass, which does not seem to be the intended behavior.

This seems to be an issue as of commit 1965b5 (switching back to webpack)

**Comment by stefnotch** [comment] 2017-10-17 15:55
Can also reproduce this issue.

**Comment by kevzettler** [comment] 2017-10-18 04:23
ok confirming this is a real issue

I have isolated an broken a test case:
```
    describe.only("fromValues", function() {
        beforeEach(function() { result = vec2.fromValues(1, 2); });
        it("should return a 2 element array initialized to the values passed", function() { expect(result).toBeEqualish([1, 3]); });
    });
```

produces false positive output
```
> gl-matrix@2.4.0 test /Users/kev/code/gl-matrix
> mocha --compilers js:babel-register --recursive spec



  vec2
    fromValues
      ✓ should return a 2 element array initialized to the values passed


  1 passing (162ms)
```

**Comment by stefnotch** [comment] 2017-10-18 12:45
@toji This issue is most likely caused by switching to **mocha** from **jasmine**.
File: https://github.com/toji/gl-matrix/blob/master/package.json 
Commit: https://github.com/toji/gl-matrix/commit/1965b52a3c3f5c05b846245efc9bcbe510924a74#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Mocha wants the [tests to actually throw an exception](https://mochajs.org/#assertions), in order for them to fail. So, this could be fixed by rewriting spec-helper.js.

**Comment by kevzettler** [comment] 2017-10-18 16:10
@stefnotch is correct. the issue stems from `spec-helper.js` and I believe the transition from jasmine to mocha. Mocha expects an exception to be raised when asserting.  I have made an attempt to wrap all the expect functions in an assert in https://github.com/toji/gl-matrix/pull/263

**Comment by stefnotch** [comment] 2017-10-30 17:51
@toji @sinisterchipmunk This issue has been resolved and can be closed

**Comment by stefnotch** [comment] 2018-03-04 09:36
@jvorob Would you mind closing this issue since it has been resolved.

**Closed** 2018-03-06 21:23 UTC
